import { MessageType } from './types';

export const Messages: MessageType[] = [
  {
    id: 0,
    message: 'hej',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 1,
    message: 'yo',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 2,
    message: 'aaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 3,
    message: 'aaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 4,
    message: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 5,
    message: 'mhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 6,
    message: 'mmhhhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 7,
    message: 'aaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 8,
    message: 'aaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 9,
    message: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 10,
    message: 'mhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 11,
    message: 'mmhhhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 12,
    message: 'aaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 13,
    message: 'aaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 14,
    message: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 15,
    message: 'mhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 16,
    message: 'mmhhhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 17,
    message: 'aaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 18,
    message: 'aaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 19,
    message: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 20,
    message: 'mhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 21,
    message: 'mmhhhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 22,
    message: 'aaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 23,
    message: 'aaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 24,
    message: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    senderName: 'accuse',
    userIsSender: false,
  },
  {
    id: 25,
    message: 'mhm',
    senderName: 'milos',
    userIsSender: true,
  },
  {
    id: 26,
    message: 'mmhhhm',
    senderName: 'milos',
    userIsSender: true,
  },
];
