export const Playlists = [
  { name: 'NewSongs', count: 10 },
  { name: 'Żuki', count: 0 },
  { name: 'Rock', count: 220 },
  { name: 'Old', count: 1 },
  { name: 'No like', count: 122220 },
  { name: 'lorem ipsum', count: 2 },
  { name: 'lorem ipsum', count: 21 },
  { name: 'lorem ipsum', count: 11 },
  { name: 'lorem ipsum', count: 23 },
  { name: 'lorem ipsum', count: 5 },
  { name: 'lorem ipsum', count: 8 },
  { name: 'lorem ipsum', count: 2 },
  { name: 'lorem ipsum', count: 21 },
  { name: 'lorem ipsum', count: 11 },
  { name: 'lorem ipsum', count: 23 },
  { name: 'lorem ipsum', count: 5 },
  { name: 'lorem ipsum', count: 8 },
  { name: 'lorem ipsum', count: 2 },
  { name: 'lorem ipsum', count: 21 },
  { name: 'lorem ipsum', count: 11 },
  { name: 'lorem ipsum', count: 23 },
  { name: 'lorem ipsum', count: 5 },
  { name: 'lorem ipsum', count: 8 },
];
